extends:
    - ./lint/eslintrc-gjs.yml
    - ./lint/eslintrc-shell.yml
    - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
plugins: ["@typescript-eslint"]
root: true
parserOptions:
    sourceType: module
rules:
    jsdoc/require-param-type: off #Not needed anymore with TypeScript source
    no-shadow: "off"
    "@typescript-eslint/no-shadow": "error"
    "@typescript-eslint/no-explicit-any": "off"
